/**
 * 
 */
package com.osterhoutgroup.sharedlibraryplugin.constants;

/**
 * @author wilbur.yu
 *
 */
public class UserAccountConstants {
	public static final int USERACCOUNT_RESULT_OK = 0x310;
	public static final int USERACCOUNT_RESULT_MISSING_DATA = USERACCOUNT_RESULT_OK + 1;
	public static final int USERACCOUNT_RESULT_UNABLE_CONNECT_DATABASE = USERACCOUNT_RESULT_OK + 2;
	public static final int USERACCOUNT_RESULT_PERMISSION_DENIED = USERACCOUNT_RESULT_OK + 3;
	public static final int USERACCOUNT_RESULT_ACCOUNT_ALREADY_EXISTED = USERACCOUNT_RESULT_OK + 4;
	public static final int USERACCOUNT_RESULT_EMAIL_ALREADY_USED = USERACCOUNT_RESULT_OK + 5;
	public static final int USERACCOUNT_RESULT_INVALID_PASSWORD_FORMAT = USERACCOUNT_RESULT_OK + 6;
	public static final int USERACCOUNT_RESULT_NOT_FOUND = USERACCOUNT_RESULT_OK + 7;
	public static final int USERACCOUNT_RESULT_INVALID_DATA = USERACCOUNT_RESULT_OK + 8;
	public static final int USERACCOUNT_RESULT_WRONG_PASSWORD = USERACCOUNT_RESULT_OK + 9;
	public static final int USERACCOUNT_RESULT_SAME_PASSWORD = USERACCOUNT_RESULT_OK + 10;
	public static final int USERACCOUNT_RESULT_EXPIRED_REFRESH_TOKEN = USERACCOUNT_RESULT_OK + 11;
	public static final int USERACCOUNT_RESULT_EXPIRED_ACCESS_TOKEN = USERACCOUNT_RESULT_OK + 12;
	public static final int USERACCOUNT_RESULT_UNABLE_CREATE_TOKEN = USERACCOUNT_RESULT_OK + 13;
}
